name: UI & API Test Automation

on:
  workflow_dispatch:  # Allows manual execution from GitHub Actions tab

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on a Linux server in GitHub Actions

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Checkout code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up Python environment
      with:
        python-version: '3.9'  # Use Python 3.9

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies
        pip install chromedriver-autoinstaller  # Ensure ChromeDriver is installed

    - name: Run UI & API Tests with Allure
      run: |
        pytest --alluredir=allure-results --capture=sys  # Run tests and store Allure results

    - name: Install Allure CLI
      run: |
        sudo apt update
        sudo apt install -y default-jre  # Ensure Java is installed (Allure requires Java)
        wget -O allure.tgz https://github.com/allure-framework/allure2/releases/latest/download/allure-2.24.0.tgz
        tar -zxvf allure.tgz
        sudo mv allure-2.24.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
        allure --version  # Verify installation

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report  # Convert JSON results to an HTML report

    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report  # Upload generated report
