name: UI & API Test Automation

on:
  push:
    branches:
      - main  # Runs on push to main
  pull_request:
    branches:
      - main  # Runs on pull requests

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on a Linux server in GitHub Actions

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Updated checkout action

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated setup-python action
      with:
        python-version: '3.9'  # Use Python 3.9

    - name: Verify requirements.txt exists
      run: |
        if [ ! -f requirements.txt ]; then
          echo "requirements.txt not found! Exiting...";
          exit 1;
        else
          echo "requirements.txt found!";
        fi

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt  # Install project dependencies
        pip install pytest               # Ensure pytest is installed

    - name: Run UI & API Tests
      run: |
        pytest --html=report.html  # Run tests and generate HTML report

    - name: Upload Test Report
      uses: actions/upload-artifact@v4  # ✅ Updated upload-artifact action
      with:
        name: test-report
        path: report.html  # Uploads test report as an artifact
