name: UI & API Test Automation

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on a Linux server in GitHub Actions

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Checkout code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up Python environment
      with:
        python-version: '3.9'  # Use Python 3.9

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies

    - name: Run UI & API Tests with Custom Styling
      run: |
        pytest --html=report.html --self-contained-html --css=custom_style.css --capture=sys
