name: UI & API Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on a Linux server in GitHub Actions

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Checkout action to get the code

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up Python environment
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        pip install chromedriver-autoinstaller  # Install chromedriver autoinstaller

    - name: Run UI & API Tests
      run: |
        pytest --html=report.html  # Run tests and generate HTML report

    - name: Upload Test Report
      uses: actions/upload-artifact@v4  # Upload test report as an artifact
      with:
        name: test-report
        path: report.html  # Upload the HTML report
