name: UI & API Test Automation

on:
  push:
    branches:
      - main  # Run tests when code is pushed to main
  pull_request:
    branches:
      - main  # Run tests when a pull request is created for main

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on a Linux server in GitHub Actions

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Fetch latest code from GitHub

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Python version for the project

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies

    - name: Run UI & API Tests
      run: |
        pytest --html=report.html  # Run tests & generate report

    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: report.html  # Store test report as an artifact
